[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --html=reports/test_report.html --self-contained-html --cov=. --cov-report=html --cov-report=term
